name: "Deploy infrastructure with terraform"

on:
  workflow_dispatch:

jobs:
  image-build-job:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secrete_key }}
      AWS_REGION: "ap-northeast-1"
      TERRAFORM_VERSION: "1.8.5"

    steps:

      - name: "Checkout source code"
        uses: actions/checkout@v4

      - name: "Installing Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: "Terraform Init"
        run: terraform init
        working-directory: ./terraform/

      - name: "Terraform Fmt"
        run: terraform fmt
        working-directory: ./terraform/

      - name: "Terraform Validate"
        run: terraform validate
        working-directory: ./terraform/

      - name: "Terraform Plan"
        run: terraform plan
        working-directory: ./terraform/

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
        working-directory: ./terraform/

